### ISSUE TITLE
Updating certificates fails

### ISSUE THREAD

**Issue by sascha-andres** [rancher-sandbox/rancher-desktop#2778]
### Actual Behavior

Rancher not starting

### Steps to Reproduce

Start Rancher Desktop

### Result

2022-08-19T07:27:00.315Z: Registered distributions: Ubuntu-20.04,rancher-desktop-data,rancher-desktop
2022-08-19T07:27:00.570Z: Registered distributions: Ubuntu-20.04,rancher-desktop-data,rancher-desktop
2022-08-19T07:27:01.006Z: Registered distributions: Ubuntu-20.04,rancher-desktop-data,rancher-desktop
2022-08-19T07:27:01.199Z: Registered distributions: Ubuntu-20.04,rancher-desktop-data,rancher-desktop
2022-08-19T07:27:01.199Z: data distro already registered
2022-08-19T07:27:16.466Z: Installing C:\Users\sascha.andres\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\internal\trivy as /mnt/c/Users/sascha.andres/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/internal/trivy into /usr/local/bin/trivy ...
2022-08-19T07:27:16.486Z: Installing C:\Users\sascha.andres\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\internal\rancher-desktop-guestagent as /mnt/c/Users/sascha.andres/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/internal/rancher-desktop-guestagent into /usr/local/bin//rancher-desktop-guestagent ...
2022-08-19T07:27:17.555Z: WSL: executing: /usr/sbin/update-ca-certificates: Error: wsl.exe exited with code 1

### Expected Behavior

Rancher Desktop starting and usable

### Rancher Desktop Version

1.5.1

### Rancher Desktop K8s Version

unknown

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11

### What CPU architecture are you using?

x64

**Comment by sascha-andres** [comment]
I found kind of a workaround: a complete factory reset. Not happy with that though

**Comment by adamkpickering** [comment]
Thanks for filing an issue! Is there any chance you have more details about the failure? It seems that a updating CA certificates inside a WSL distro failed, but it is tough to say what the problem is without more info. If you can get the error again, could you please do the following:
- enable debug mode in the Troubleshooting tab
- get RD to produce the error
- upload your logs here (you can get to the folder with the logs via a button in the Troubleshooting tab)

Thanks!

**Comment by sascha-andres** [comment]
Will do so tomorrow (I'm back in the office then)

**Comment by sascha-andres** [comment]
Actually the steps resulted in a completely unusable state:

![image](https://user-images.githubusercontent.com/3052075/186150280-99c033c1-1472-45f2-adbc-45289a008a09.png)

After pressing OK the app is closed. After I stopped wsl completely I could remove the file and start it again.

Logs attached

[logs.zip](https://github.com/rancher-sandbox/rancher-desktop/files/9402220/logs.zip)

**Comment by adamkpickering** [comment]
That's fishy. Were you running RD as an administrator by any chance? It must be run as a regular user.

**Comment by sascha-andres** [comment]
@adamkpickering sorry for the late reply, was sick. No, I was not using RD as an administrator. We have no administrative rights here

**Comment by adamkpickering** [comment]
So WSL is installed for you? That EPERM exception makes me wonder if IT has your system super locked down. Though I'm not very knowledgeable about Windows... @mook-as what is your take on this?

**Comment by mook-as** [comment]
The `EPERM` can occur if you somehow managed to start Rancher Desktop twice (because the previous instance has the file open, the new instance can't delete it).

It's unclear why running `update-ca-certificates` is failing, though; `wsl-exec.log` shows:
> run-parts: /etc/ca-certificates/update.d/certhash: exit status 132

But it's unclear why that's happening.  Would you be able to (once the failure has occurred) manually run `update-ca-certificates` in the `rancher-desktop` WSL distribution, and dig into the errors there?

**Comment by cyron7** [comment]
[wsl-exec.log](https://github.com/rancher-sandbox/rancher-desktop/files/9726430/wsl-exec.log)

**Comment by mook-as** [comment]
> `/etc/ca-certificates/update.d/certhash: exit status 132`

>     # cat /etc/ca-certificates/update.d/certhash
>     #!/bin/sh
>     exec /usr/bin/c_rehash /etc/ssl/certs

Alpine has their own [`c_rehash`](https://gitlab.alpinelinux.org/alpine/ca-certificates/-/blob/master/c_rehash.c); it's not clear how that can exist with 132 — it looks like it returns either 2 or 0.  It's also possible it's actually (128 + 4), in which case it's `SIGILL`… which also doesn't make much sense.

Please try running `/usr/bin/c_rehash -v /etc/ssl/certs` manually and see if it produces more details?

Out of curiosity, what CPU do you have? Not that I _really_ expect a missing instruction there…  The other option I see is corruption (either disk image or memory).

**Comment by cyron7** [comment]
See log for results of command '/usr/bin/c_rehash -v /etc/ssl/certs' run from within 'rancher-desktop'

[c_rehash.log](https://github.com/rancher-sandbox/rancher-desktop/files/9728087/c_rehash.log)

**Comment by cyron7** [comment]
CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by mook-as** [comment]
> `Illegal instruction`

Well, that's interesting!
`c_rehash` (for 1.5.1) has a sha256 hash of `3AD730F1AE440CAE63D0C4E5EECFB3A69318E5FABE2E10B16BBCDA81735A8E7C` for me. Is yours any different?

That CPU shouldn't be missing any actual instructions, as far as I know…

**Comment by jandubois** [comment]
@cyron7 Could you run `/usr/bin/openssl rehash -v /etc/ssl/certs` to see if it fails the same way?

Also, could you attach the output of `cat /proc/cpuinfo`? Your CPU should have all required features, so I don't really understand how this can happen.

**Comment by cyron7** [comment]
@jandubois ; I am away from that machine. I should be able to get that output to you in the next 24 hours.

**Comment by cyron7** [comment]
@mook-as ; I'm not sure how to check that. I'll to to figure that out and get back with you.

**Comment by jandubois** [comment]
> I'm not sure how to check that. I'll to to figure that out and get back with you.

Some options:

```console
lima-rancher-desktop:~$ sha256sum /usr/bin/c_rehash
3ad730f1ae440cae63d0c4e5eecfb3a69318e5fabe2e10b16bbcda81735a8e7c  /usr/bin/c_rehash
lima-rancher-desktop:~$ openssl dgst -sha256 /usr/bin/c_rehash
SHA256(/usr/bin/c_rehash)= 3ad730f1ae440cae63d0c4e5eecfb3a69318e5fabe2e10b16bbcda81735a8e7c
```

@mook-as shows an uppercase hash, so not sure which command he ran. 😄

**Comment by cyron7** [comment]
@jandubois ; I looks like that is missing:
![image](https://user-images.githubusercontent.com/19749973/194558457-92db2cc8-c8e9-4938-ba16-74ee23bfb012.png)

**Comment by cyron7** [comment]
@jandubois ; Here is the information from cpuinfo:
[cpuinfo.log](https://github.com/rancher-sandbox/rancher-desktop/files/9734054/cpuinfo.log)

**Comment by cyron7** [comment]
@jandubois and @mook-as ; This was the output from running the rehash:
![image](https://user-images.githubusercontent.com/19749973/194558987-9e90fdc6-963c-43a9-a614-1e50037e70c0.png)

**Comment by jandubois** [comment]
> Here is the information from cpuinfo:

Thanks! That all looks as expected (VM settings match your host CPU), and all the features like sse4_2 and avx are there, so not giving any clue...

**Comment by cyron7** [comment]
Is there any network requirements for Rancher to be able to start up or for the update-ca-certificates to work?

**Comment by jandubois** [comment]
> Is there any network requirements for Rancher to be able to start up or for the update-ca-certificates to work?

No, it should work fine without network. Of course you will need a network connection to download images, and to fetch the Kubernetes version you want to run, but if they already exist locally, then you can run offline.

**Comment by jandubois** [comment]
Ok, maybe test just an empty Alpine distro and see if that already fails, or if the issue is with stuff that gets installed later.

Can you run these commands and show if they succeed or fail:

```console
PS C:\Users\Jan> wsl --import testing . '.\AppData\Local\Programs\Rancher Desktop\resources\resources\win32\distro-0.27.tar'
PS C:\Users\Jan> wsl -d testing update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
PS C:\Users\Jan> wsl --unregister testing
Unregistering...
```

The `distro-0.27` filename assumes that you are trying Rancher Desktop 1.6.0 now. If you are still on 1.5.1 then the version should be 0.26.

If you get a failure from this test too, please uninstall 1.5.1 and install 1.6.0 and try again.  I kind of doubt that there are any differences, but the time has come for desperate actions...

**Comment by cyron7** [comment]
@jandubois ; Sorry I took so long getting back to you. I got the same error. I am using 1.5.1. I will update to 1.6.0 and see if that solves the problem: 
![image](https://user-images.githubusercontent.com/19749973/195137983-2059013e-8311-4806-9373-8f36441e2e7a.png)

**Comment by cyron7** [comment]
@jandubois ; I uninstalled 1.5.1 and installed 1.6.0. The same symptoms happened where I can initially get Rancher to start but after I shutdown and start up my host machine I get the update-ca-certificates error. I tried the command you suggested on 1.6.0 and got the same error with distro 27 as I did with 26:
![image](https://user-images.githubusercontent.com/19749973/195169013-0fa1e24b-2d99-43aa-8ce1-5c41abb52e7f.png)

**Comment by jandubois** [comment]
This shows that the error is not triggered with just the builtin certs from the distro, so I think this means it is related to one of the certs on your host that is being copied into the distro as Rancher Desktop starts up.

@mook-as Do you have any idea how to isolate the cert that may be triggering this?

**Comment by cyron7** [comment]
As a slightly separate topic, I noticed that after the error, Rancher doesn't notice that this blocked the daemon isn't running:
![image](https://user-images.githubusercontent.com/19749973/195635665-d65037a9-e2dc-4981-a1ba-10c7399d29c5.png)

**Comment by jandubois** [comment]
> As a slightly separate topic, I noticed that after the error, Rancher doesn't notice that this blocked the daemon from running:

Yes, we just implemented the framework for providing diagnostics; how to alert the user, and how to manage them. The 1.6.0 release only contains a handful (quite literally) of diagnostics, mostly related to `PATH` configuration. We will expand the set of diagnostics over time.

**Comment by mook-as** [comment]
Hmm, other than the output from `/usr/bin/c_rehash -v /etc/ssl/certs` (which you've already done) I don't have a better idea to isolate the failure except to binary search (delete half the certs in `/usr/local/share/ca-certificates`, see if that fails, and repeat until you narrow it down to one file).

**Comment by cyron7** [comment]
@mook-as I did that initially and thought it was certs 300 - 399. Then I noticed that when I removed all of them except cert 0 it would work. Then it would rebuild them (the certificates) all and Rancher Desktop would crash. That's where I got the idea of just removing them all. Thinking that it could be a potential workaround or clue to what is happening. Now it doesn't matter what certificates I remove. I know there was an idea proposed by @adamkpickering that maybe something on my machine was so locked down that it was breaking Rancher. I don't know if there is something one of you want me to try to see if something is indeed blocking Rancher.

**Comment by cyron7** [comment]
I wanted to mention that I updated to version 1.6.1 and the issue is still there:
![image](https://user-images.githubusercontent.com/19749973/198709057-f22c5002-abfd-4f4e-b593-45fe75639e75.png)

**Comment by craigforr** [comment]
I have the exact same issue on Windows 10...

## Windows specifications

```
Edition: Windows 10 Enterprise
Version: 22H2
Installed on: 12/22/2021
OS build: 19045.2251
Experience: Windows Feature Experience Pack 120.2212.4180.0
```

## Error

```
2022-12-14T15:38:36.167Z: Registered distributions: rancher-desktop
2022-12-14T15:38:41.867Z: /sbin/init exited gracefully.
2022-12-14T15:38:42.542Z: Registered distributions: Ubuntu,rancher-desktop,Ubuntu-20.04,Ubuntu-18.04
2022-12-14T15:38:43.863Z: Registered distributions: Ubuntu,rancher-desktop-data,rancher-desktop,Ubuntu-20.04,Ubuntu-18.04
2022-12-14T15:38:44.781Z: Registered distributions: Ubuntu,rancher-desktop-data,rancher-desktop,Ubuntu-20.04,Ubuntu-18.04
2022-12-14T15:38:45.760Z: Registered distributions: Ubuntu,rancher-desktop-data,rancher-desktop,Ubuntu-20.04,Ubuntu-18.04
2022-12-14T15:38:45.760Z: data distro already registered
2022-12-14T15:39:15.168Z: Installing C:\Users\user1\AppData\Local\Programs\Rancher Desktop\resources\resources\linux\internal\trivy as /mnt/c/Users/user1/AppData/Local/Programs/Rancher Desktop/resources/resources/linux/internal/trivy into /usr/local/bin/trivy ...
2022-12-14T15:39:18.400Z: WSL: executing: /usr/sbin/update-ca-certificates: Error: wsl.exe exited with code 1
```

## Background

I have been getting this error consistently beginning this week.  The only work-around that I have found which will get RD to start successfully is a Factory Reset.

The odd thing is that the error is listed as "Error Starting Kubernetes" and I get the error whether Kubernetes is enabled or not.

I have stopped Rancher Desktop and saved all of the logs from this point in time if you would like additional details from the logs, @jandubois.

Craig

**Comment by svendhoest** [comment]
I got the same issue after rebooting.

`PS C:\git\FitXP_Main> wsl.exe --distribution rancher-desktop --exec /usr/sbin/update-ca-certificates
WARNING: Skipping duplicate certificate in file ca-cert-rd-428.pem
WARNING: Skipping duplicate certificate in file ca-cert-Go_Daddy_Root_Certificate_Authority_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-480.pem
WARNING: Skipping duplicate certificate in file ca-cert-COMODO_Certification_Authority.pem
WARNING: ca-cert-rd-366.pem does not contain exactly one certificate or CRL: skipping
WARNING: Skipping duplicate certificate in file ca-cert-rd-470.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-483.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-375.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-404.pem
WARNING: Skipping duplicate certificate in file ca-cert-T-TeleSec_GlobalRoot_Class_2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-497.pem
WARNING: Skipping duplicate certificate in file ca-cert-OISTE_WISeKey_Global_Root_GB_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-448.pem
WARNING: Skipping duplicate certificate in file ca-cert-Microsec_e-Szigno_Root_CA_2009.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-393.pem
WARNING: Skipping duplicate certificate in file ca-cert-OISTE_WISeKey_Global_Root_GC_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-63.pem
WARNING: Skipping duplicate certificate in file ca-cert-Comodo_AAA_Services_root.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-462.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-338.pem
WARNING: Skipping duplicate certificate in file ca-cert-TrustAsia_Global_Root_CA_G4.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-410.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-331.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-383.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority_-_EC1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-513.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-368.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-455.pem
WARNING: Skipping duplicate certificate in file ca-cert-COMODO_ECC_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-501.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-493.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Assured_ID_Root_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-28.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-436.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-482.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-92.pem
WARNING: Skipping duplicate certificate in file ca-cert-Atos_TrustedRoot_Root_CA_RSA_TLS_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-Sectigo_Public_Server_Authentication_Root_E46.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-372.pem
WARNING: Skipping duplicate certificate in file ca-cert-certSIGN_ROOT_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-BJCA_Global_Root_CA1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-377.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-426.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-468.pem
WARNING: Skipping duplicate certificate in file ca-cert-GTS_Root_R2.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certum_Trusted_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Assured_ID_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority_-_G4.pem
WARNING: Skipping duplicate certificate in file ca-cert-emSign_Root_CA_-_C1.pem
WARNING: Skipping duplicate certificate in file ca-cert-TrustAsia_Global_Root_CA_G3.pem
WARNING: Skipping duplicate certificate in file ca-cert-TeliaSonera_Root_CA_v1.pem
WARNING: Skipping duplicate certificate in file ca-cert-certSIGN_Root_CA_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-ACCVRAIZ1.pem
WARNING: Skipping duplicate certificate in file ca-cert-TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
WARNING: Skipping duplicate certificate in file ca-cert-SecureTrust_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_CA_-_R6.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-510.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-361.pem
WARNING: Skipping duplicate certificate in file ca-cert-ISRG_Root_X1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-449.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-430.pem
WARNING: Skipping duplicate certificate in file ca-cert-emSign_ECC_Root_CA_-_C3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Security_Communication_RootCA3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Amazon_Root_CA_4.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-412.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-349.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-485.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-476.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certigna_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certum_Trusted_Network_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-394.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-441.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-363.pem
WARNING: Skipping duplicate certificate in file ca-cert-Actalis_Authentication_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-427.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-392.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-369.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-489.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-381.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certum_EC-384_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-399.pem
WARNING: Skipping duplicate certificate in file ca-cert-SSL.com_Root_Certification_Authority_ECC.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-446.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-502.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-477.pem
WARNING: Skipping duplicate certificate in file ca-cert-Atos_TrustedRoot_Root_CA_ECC_TLS_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-418.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-336.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-409.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-364.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-396.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-376.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-467.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-333.pem
WARNING: Skipping duplicate certificate in file ca-cert-SwissSign_Gold_CA_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-337.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-512.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-416.pem
WARNING: Skipping duplicate certificate in file ca-cert-D-TRUST_BR_Root_CA_1_2020.pem
WARNING: Skipping duplicate certificate in file ca-cert-Trustwave_Global_ECC_P256_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-499.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-330.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-402.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-442.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-439.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-389.pem
WARNING: Skipping duplicate certificate in file ca-cert-GDCA_TrustAUTH_R5_ROOT.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-440.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_E46.pem
WARNING: Skipping duplicate certificate in file ca-cert-HARICA_TLS_ECC_Root_CA_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-382.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-85.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-495.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-408.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certainly_Root_R1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-432.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_G3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-424.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-406.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-511.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-360.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Assured_ID_Root_G3.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-407.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-453.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-328.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-341.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-339.pem
WARNING: Skipping duplicate certificate in file ca-cert-CommScope_Public_Trust_ECC_Root-02.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-329.pem
WARNING: Skipping duplicate certificate in file ca-cert-ANF_Secure_Server_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-373.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-429.pem
WARNING: Skipping duplicate certificate in file ca-cert-UCA_Global_G2_Root.pem
WARNING: Skipping duplicate certificate in file ca-cert-SZAFIR_ROOT_CA2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-378.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_TLS_ECC_P384_Root_G5.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-386.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-422.pem
WARNING: Skipping duplicate certificate in file ca-cert-AffirmTrust_Networking.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-379.pem
WARNING: Skipping duplicate certificate in file ca-cert-Buypass_Class_2_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-435.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-487.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-456.pem
WARNING: Skipping duplicate certificate in file ca-cert-Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-488.pem
WARNING: Skipping duplicate certificate in file ca-cert-CommScope_Public_Trust_ECC_Root-01.pem
WARNING: Skipping duplicate certificate in file ca-cert-Hongkong_Post_Root_CA_3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Baltimore_CyberTrust_Root.pem
WARNING: Skipping duplicate certificate in file ca-cert-AffirmTrust_Commercial.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-417.pem
WARNING: Skipping duplicate certificate in file ca-cert-Trustwave_Global_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-405.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Trusted_Root_G4.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-390.pem
WARNING: Skipping duplicate certificate in file ca-cert-Security_Communication_RootCA2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-503.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-355.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-335.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-345.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_High_Assurance_EV_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-Atos_TrustedRoot_2011.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-347.pem
WARNING: Skipping duplicate certificate in file ca-cert-XRamp_Global_CA_Root.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_ECC_Root_CA_-_R4.pem
WARNING: Skipping duplicate certificate in file ca-cert-USERTrust_RSA_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-463.pem
WARNING: Skipping duplicate certificate in file ca-cert-Microsoft_ECC_Root_Certificate_Authority_2017.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-400.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-481.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-395.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-469.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-438.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-491.pem
WARNING: Skipping duplicate certificate in file ca-cert-ePKI_Root_Certification_Authority.pem
run-parts: /etc/ca-certificates/update.d/certhash: exit status 132`

**Comment by egorshulga** [comment]
I performed a complete reset of WSL and reinstallation of Rancher, but the same error started to appear again, and Rancher can't start up 👀
Did I miss sth, is there a workaround found?

The command shown in the error dialog indeed fails

```powershell
C:\Users\...> wsl.exe --distribution rancher-desktop --exec /usr/sbin/update-ca-certificates
WARNING: Skipping duplicate certificate in file ca-cert-rd-422.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-394.pem
WARNING: Skipping duplicate certificate in file ca-cert-SSL.com_EV_Root_Certification_Authority_ECC.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-528.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-515.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-434.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-501.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-454.pem
WARNING: Skipping duplicate certificate in file ca-cert-IdenTrust_Public_Sector_Root_CA_1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-459.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-545.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-555.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Assured_ID_Root_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-386.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-460.pem
WARNING: Skipping duplicate certificate in file ca-cert-HARICA_TLS_ECC_Root_CA_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-384.pem
WARNING: Skipping duplicate certificate in file ca-cert-D-TRUST_Root_Class_3_CA_2_EV_2009.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-444.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-558.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-412.pem
WARNING: Skipping duplicate certificate in file ca-cert-NAVER_Global_Root_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-479.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-476.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-565.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-429.pem
WARNING: Skipping duplicate certificate in file ca-cert-Microsoft_ECC_Root_Certificate_Authority_2017.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-540.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-451.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-511.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-494.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-507.pem
WARNING: Skipping duplicate certificate in file ca-cert-QuoVadis_Root_CA_2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-402.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-389.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-452.pem
WARNING: Skipping duplicate certificate in file ca-cert-certSIGN_Root_CA_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-430.pem
WARNING: Skipping duplicate certificate in file ca-cert-HARICA_TLS_RSA_Root_CA_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-AffirmTrust_Commercial.pem
WARNING: Skipping duplicate certificate in file ca-cert-GLOBALTRUST_2020.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Assured_ID_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-527.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-448.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-468.pem
WARNING: Skipping duplicate certificate in file ca-cert-CommScope_Public_Trust_ECC_Root-02.pem
WARNING: Skipping duplicate certificate in file ca-cert-SecureTrust_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-CommScope_Public_Trust_ECC_Root-01.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-450.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-485.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-401.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-509.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority_-_EC1.pem
WARNING: Skipping duplicate certificate in file ca-cert-SSL.com_EV_Root_Certification_Authority_RSA_R2.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_ECC_Root_CA_-_R4.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-531.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust.net_Premium_2048_Secure_Server_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-554.pem
WARNING: Skipping duplicate certificate in file ca-cert-vTrus_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-emSign_ECC_Root_CA_-_C3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Sectigo_Public_Server_Authentication_Root_E46.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-458.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-372.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-438.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-537.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-416.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-375.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-550.pem
WARNING: Skipping duplicate certificate in file ca-cert-XRamp_Global_CA_Root.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-461.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-466.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-414.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-380.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-415.pem
WARNING: Skipping duplicate certificate in file ca-cert-SwissSign_Silver_CA_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-532.pem
WARNING: Skipping duplicate certificate in file ca-cert-SSL.com_Root_Certification_Authority_ECC.pem
WARNING: Skipping duplicate certificate in file ca-cert-TrustAsia_Global_Root_CA_G4.pem
WARNING: Skipping duplicate certificate in file ca-cert-COMODO_RSA_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-502.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-410.pem
WARNING: Skipping duplicate certificate in file ca-cert-Telekom_Security_TLS_ECC_Root_2020.pem
WARNING: Skipping duplicate certificate in file ca-cert-Atos_TrustedRoot_Root_CA_ECC_TLS_2021.pem
WARNING: Skipping duplicate certificate in file ca-cert-AC_RAIZ_FNMT-RCM.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-453.pem
WARNING: Skipping duplicate certificate in file ca-cert-Go_Daddy_Root_Certificate_Authority_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-CFCA_EV_ROOT.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-486.pem
WARNING: Skipping duplicate certificate in file ca-cert-Comodo_AAA_Services_root.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-557.pem
WARNING: Skipping duplicate certificate in file ca-cert-Microsoft_RSA_Root_Certificate_Authority_2017.pem
WARNING: Skipping duplicate certificate in file ca-cert-Trustwave_Global_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-Microsec_e-Szigno_Root_CA_2009.pem
WARNING: Skipping duplicate certificate in file ca-cert-CA_Disig_Root_R2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-504.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-387.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-498.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-553.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-563.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-495.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-456.pem
WARNING: Skipping duplicate certificate in file ca-cert-Amazon_Root_CA_2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-377.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-376.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-478.pem
WARNING: Skipping duplicate certificate in file ca-cert-emSign_ECC_Root_CA_-_G3.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_High_Assurance_EV_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-544.pem
WARNING: Skipping duplicate certificate in file ca-cert-GTS_Root_R2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-521.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-470.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-465.pem
WARNING: Skipping duplicate certificate in file ca-cert-Amazon_Root_CA_1.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-399.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-371.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certainly_Root_R1.pem
WARNING: Skipping duplicate certificate in file ca-cert-ePKI_Root_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-408.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_R46.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-404.pem
WARNING: Skipping duplicate certificate in file ca-cert-OISTE_WISeKey_Global_Root_GC_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_G3.pem
WARNING: Skipping duplicate certificate in file ca-cert-SSL.com_Root_Certification_Authority_RSA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-423.pem
WARNING: Skipping duplicate certificate in file ca-cert-TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
WARNING: Skipping duplicate certificate in file ca-cert-BJCA_Global_Root_CA2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-441.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-440.pem
WARNING: ca-cert-rd-418.pem does not contain exactly one certificate or CRL: skipping
WARNING: Skipping duplicate certificate in file ca-cert-rd-562.pem
WARNING: Skipping duplicate certificate in file ca-cert-DigiCert_Global_Root_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-395.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certum_EC-384_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-457.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-455.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-437.pem
WARNING: Skipping duplicate certificate in file ca-cert-IdenTrust_Commercial_Root_CA_1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-489.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-393.pem
WARNING: Skipping duplicate certificate in file ca-cert-Entrust_Root_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-505.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-514.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-299.pem
WARNING: Skipping duplicate certificate in file ca-cert-ISRG_Root_X2.pem
WARNING: Skipping duplicate certificate in file ca-cert-ISRG_Root_X1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-391.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-421.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-473.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-469.pem
WARNING: Skipping duplicate certificate in file ca-cert-Go_Daddy_Class_2_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-378.pem
WARNING: Skipping duplicate certificate in file ca-cert-Secure_Global_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certigna_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-Trustwave_Global_ECC_P384_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-549.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-267.pem
WARNING: Skipping duplicate certificate in file ca-cert-Starfield_Root_Certificate_Authority_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-HiPKI_Root_CA_-_G1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-542.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-472.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-374.pem
WARNING: Skipping duplicate certificate in file ca-cert-SwissSign_Gold_CA_-_G2.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-539.pem
WARNING: Skipping duplicate certificate in file ca-cert-GlobalSign_Root_E46.pem
WARNING: Skipping duplicate certificate in file ca-cert-ANF_Secure_Server_Root_CA.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-475.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-541.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-382.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-543.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-487.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-488.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-497.pem
WARNING: Skipping duplicate certificate in file ca-cert-Izenpe.com.pem
WARNING: Skipping duplicate certificate in file ca-cert-Certainly_Root_E1.pem
WARNING: Skipping duplicate certificate in file ca-cert-Atos_TrustedRoot_2011.pem
WARNING: Skipping duplicate certificate in file ca-cert-QuoVadis_Root_CA_3.pem
WARNING: Skipping duplicate certificate in file ca-cert-Trustwave_Global_ECC_P256_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-ACCVRAIZ1.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-413.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-464.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-477.pem
WARNING: Skipping duplicate certificate in file ca-cert-COMODO_Certification_Authority.pem
WARNING: Skipping duplicate certificate in file ca-cert-rd-428.pem
run-parts: /etc/ca-certificates/update.d/certhash: exit status 132
PS C:\Users\...> $LASTEXITCODE
1
```

**Comment by egorshulga** [comment]
Unfortunately now it breaks every day 😔 - the only way how I can make it working again is to perform the complete reset every morning. Have not found another workaround...

Will also try to find another substitute for Docker Desktop - Rancher was the candidate, but now it just does not work reliably anymore...
