### ISSUE TITLE
macOS Ventura: Support for running x86-64 binaries with Rosetta 2

### ISSUE THREAD

**Issue by reppners** [rancher-sandbox/rancher-desktop#3107]
### Problem Description

Currently on Apple Silicon x86 binaries/containers only can be run with qemu but qemu sometimes crashes or glitches out.

### Proposed Solution

With macOS Ventura it becomes possible to apply Rosetta 2 in virtualized environments.
See https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta?language=objc

### Additional Information

See the same request in context of Docker Desktop: https://github.com/docker/roadmap/issues/384

**Comment by jandubois** [comment]
It should probably go into Lima (I already mentioned it in https://github.com/lima-vm/lima/issues/889#issuecomment-1153010671). It is definitely on my radar, as I expect to have a machine running Ventura soonish.

**Comment by AkihiroSuda** [comment]
> Currently on Apple Silicon x86 binaries/containers only can be run with qemu but qemu sometimes crashes or glitches out.


Is Rosetta 2 more stable than QEMU?

**Comment by danielhodder** [comment]
Seems like all the required changes have now landed in Lima. Testing the docker engine inside a Lima VM seems to show much better compatibility.

Very much looking forward to when this lands in Rancher Desktop.

**Comment by kalavt** [comment]
LIMA has support to `Virtualization.framework` from [release v0.14.0](https://github.com/lima-vm/lima/releases/tag/v0.14.0)

**Comment by danielhodder** [comment]
Is there anything the community at large could help with to get this into the next release of Rancher Desktop? I am sure there are a lot of people who really are looking forward to this feature, and would be happy to help out if we knew what to do.

**Comment by jandubois** [comment]
Latest status: https://github.com/rancher-sandbox/rancher-desktop/issues/3537#issuecomment-1440445440

**Comment by reppners** [comment]
I've installed Ventura, Rosetta2 and RD 1.8.0 with settings

```
rdctl set --experimental.virtual-machine.type vz
rdctl set --experimental.virtual-machine.use-rosetta
```

and tested with `docker run -it --platform linux/amd64 ubuntu` to check if rosetta is being used, however I see

```
root@95a56ee40f11:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 10:46 pts/0    00:00:00 /usr/bin/qemu-x86_64 /bin/bash /bin/bash
root        14     1  0 10:47 ?        00:00:00 ps -ef
```

My guess now is I'm being too early and something is still missing. If otherwise, please let me know 😅

**Comment by nathanpiper** [comment]
I confirmed that out of the box, with the experimental settings enabled QEMU is still used. I'm not sure how Rancher Desktop  calls lima to configure the VM, but it seems you need to also [set "$LIMA_CIDATA_ROSETTA_BINFMT=true"](https://raw.githubusercontent.com/lima-vm/lima/69d032b8e65ad9966f4320b4e32497ed83dc20cc/pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh).

It looks like binfmt in the VM isn't configured to register rosetta for handling x86_64 binaries.

Running the following worked for me:

First shell into the VM:
`rdctl shell`

Then run the following on the VM:
```
sudo -s
service qemu-binfmt stop
echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register
```

**Comment by nathanpiper** [comment]
On further investigation, it looks like it is configured properly but the boot script (`05-rosetta-volume.sh`) is running before procfs has started?
In `/var/log/lima-init.log`:

`/mnt/lima-cidata/boot/05-rosetta-volume.sh: line 13: can't create /proc/sys/fs/binfmt_misc/register: nonexistent directory`

**Comment by getsomebread** [comment]
> I confirmed that out of the box, with the experimental settings enabled QEMU is still used. I'm not sure how Rancher Desktop calls lima to configure the VM, but it seems you need to also [set "$LIMA_CIDATA_ROSETTA_BINFMT=true"](https://raw.githubusercontent.com/lima-vm/lima/69d032b8e65ad9966f4320b4e32497ed83dc20cc/pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh).
> 
> It looks like binfmt in the VM isn't configured to register rosetta for handling x86_64 binaries.
> 
> Running the following worked for me:
> 
> First shell into the VM: `rdctl shell`
> 
> Then run the following on the VM:
> 
> ```
> sudo -s
> service qemu-binfmt stop
> echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register
> ```
> 
> Unfortunately, this config isn't persisted after restarting Rancher Desktop / the VM.

Can confirm this is the only way I've been able to get Rosetta working with RD 1.8.1. This does not persist across reboots. A possible solution for persistence was given here, but didn't work for me: https://github.com/lima-vm/lima/issues/1443#issuecomment-1489008529

**Comment by umlx5h** [comment]
same issue.

this workaround works.
https://github.com/rancher-sandbox/rancher-desktop/issues/3107#issuecomment-1480433055

**Comment by LaurentLesle** [comment]
> ps -ef

@jandubois  - Can you run that command in the ubuntu container? Looks like from your screenshot you executed the command on your host and not within the container?

I can reproduce
![image](https://user-images.githubusercontent.com/4702224/231671312-b24b7908-7af3-4e5f-befb-8262a28e12a7.png)

And on my MAC M1
![image](https://user-images.githubusercontent.com/4702224/231671476-db4039e4-d399-4e9c-8847-3d26c5572cfe.png)

**Comment by LaurentLesle** [comment]
@getsomebread  can you expand or share the steps you did to get it working?

**Comment by getsomebread** [comment]
> @getsomebread can you expand or share the steps you did to get it working?

Sure, it requires a combination of steps from two earlier posts here. I did this with Rancher Desktop 1.8.1.
``
# Ensure you are on macOS 13/Ventura
sw_vers

# Enable experimental features, then wait for Rancher Desktop's VM to restart
rdctl set --experimental.virtual-machine.type vz
rdctl set --experimental.virtual-machine.use-rosetta

# Extra REQUIRED steps, must be done every time the VM restarts until properly fixed by developers
# Open shell into the RD VM
rdctl shell
# Become root
sudo -s
# Stop the qemu service
service qemu-binfmt stop
# Manually set this obscure setting so Rosetta works for the VM
echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register

``

**Comment by LaurentLesle** [comment]
> echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register

For some reasons the echo is failing on my machine...

```bash
  ~  sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
   ~  ~/.rd/bin/rdctl set --experimental.virtual-machine.type vz    
Status: no changes necessary.
   ~  ~/.rd/bin/rdctl set --experimental.virtual-machine.use-rosetta
Status: no changes necessary.
   ~  ~/.rd/bin/rdctl shell                                         
lima-rancher-desktop:/Users/$ sudo -s
lima-rancher-desktop:/Users/# service qemu-binfmt stop
 * Unregistering QEMU binaries in binfmt misc ...                                                                                                                                                                                                                                                                                                                                                             [ ok ]
lima-rancher-desktop:/Users/# echo ':rosetta:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/lima-rosetta/rosetta:OCF' >/proc/sys/fs/binfmt_misc/register
ash: write error: File exists
```

**Comment by valente** [comment]
> ash: write error: File exists

fyi I've been following the thread and in my first attemp I got the same error. I restarted rancher and retried and it worked. Now I see the Virtualization.framework at the top when I run the image. 🎉

**Comment by LaurentLesle** [comment]
Yes after a restart of rancher-desktop I can sudo, stop and perform the copy. I then restart the qemu-binfmt but still get the quemeu when running ps ef

docker exec -it f1a2142e95f3 /bin/zsh -c "ps ef"                                                                
  PID TTY      STAT   TIME COMMAND
    1 pts/0    Ssl+   0:00 /usr/bin/qemu-x86_64 /usr/bin/tfc-agent

**Comment by jandubois** [comment]
Will be fixed by https://github.com/lima-vm/alpine-lima/pull/103, https://github.com/lima-vm/lima/pull/1580, and #4881.

**Comment by reppners** [comment]
Thanks for making this happen! Could be quite a big quality of life improvement for my daily work 👍 

```
❯ docker run -it --platform linux/amd64 ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
6b851dcae6ca: Pull complete 
Digest: sha256:6120be6a2b7ce665d0cbddc3ce6eae60fe94637c6a66985312d1f02f63cc0bcd
Status: Downloaded newer image for ubuntu:latest
root@29b7e990e566:/# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 13:21 pts/0    00:00:00 /mnt/lima-rosetta/rosetta /bin/bash
root        10     1  0 13:21 pts/0    00:00:00 /usr/bin/ps -ef
root@29b7e990e566:/# 
```
