### ISSUE TITLE
Upgrading to from Rancher 1.16.0 => 1.17.0 cannot pull docker images from internal docker repository when connected to company VPN

### ISSUE THREAD

**Issue by jwhitmore-fleetresponse** [rancher-sandbox/rancher-desktop#8055]
### Actual Behavior

Upgrading to Rancher Desktop 1.17.0 my team and I get the following error when trying to connect to our internal docker repository 
Error response from daemon: Get https://ourlocalrepositoryname/v2/%22: dial tcp: lookup ourlocalrepositoryname on 192.168.127.1:53: no such host
Login failed.

### Steps to Reproduce

Upgrade to Rancher 1.17.0 from 1.16.0

### Result

Upgrading to Rancher Desktop 1.17.0 my team and I get the following error when trying to connect to our internal docker repository 
Error response from daemon: Get https://ourlocalrepositoryname/v2/%22: dial tcp: lookup ourlocalrepositoryname on 192.168.127.1:53: no such host
Login failed.

### Expected Behavior

Be able to connect to repository just like in version 1.16.0

### Additional Information

When my team and I downgrade to 1.16.0 we no longer have the issues and everything works fine

### Rancher Desktop Version

1.17.0

### Rancher Desktop K8s Version

1.31.4

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Enterprise v 10.0.26100

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

N/A

### Windows User Only

using OpenVPN v2.6.12

**Comment by jhollmannk** [comment]
I have the same problem and it might be a problem of the rancher-desktop WSL itself.

There is no name resolution for any host that is not explicitely in /etc/hosts.

So something like `ping www.google.com` fails with `ping: bad address 'www.google.com'`.

That happens of course also for our docker-registry host and leads to the error message mentioned above.

It also happens when I have no company VPN active, so I don't know whether this is really a factor.

I tried in another WSL to be sure and it works in all of them.

**Comment by evilhamsterman** [comment]
I think the issue is more than just not working with a VPN. The DNS seems really broken, it's broken in different ways depending on whether you have dnsTunneling=true and whether networkMode=mirrored or not. 

In trying to find a way to get DNS to work properly I basically tried every configuration of 
* dnsTunneling true || false
* networkMode true || false
* Whether the rancher-desktop WSL instance has the default `nameserver 192.168.127.1` or the nameserver for the tunnelling mode

Ultimately I didn't not find a combination where all the DNS functionality works. Sometimes it can pull containers, sometimes not. Sometimes the container will be able to resolve Internet addresses even if Docker can't pull a container, but it can't resolve VPN addresses. Sometime the Rancher Desktop WSL instance can only resolve DNS on the Internet, sometimes the internet and the VPN, sometime nothing at all.

The biggest consistency is that I could never get a container to be able to resolve a DNS on the VPN, even if the underlying Rancher Desktop instance can.

I documented everything and grabbed logs from each combination if you'd like me to add them.

**Comment by luca-ballerini** [comment]
We are seeing the same issue on macOS when upgrading from 1.16.0 to 1.17.0

**Comment by Nino-K** [comment]
@evilhamsterman could kindly attach your logs? Many thanks

**Comment by isalminen** [comment]
We are facing this same problem. Likely related to this Lima issue: https://github.com/lima-vm/lima/issues/3101
I have these message in lima.ha.stderr.log
`{"level":"debug","msg":"Error during DNS Exchange: dial udp: missing address","time":"2025-01-15T16:55:59+02:00"}`

**Comment by Nino-K** [comment]
I can confirm that the issue is caused by the recent version bump of the gvisor-tap-vsock library to [v0.8.1](https://github.com/rancher-sandbox/rancher-desktop/blob/10c1e28ec72efaa716a855bbf89578cea6aebad3/src/go/networking/go.mod#L9) as part of v1.17.0 release. To resolve this, we will need to downgrade it back to [v0.7.5](https://github.com/rancher-sandbox/rancher-desktop/blob/2fab96ec556b22babb4fda6e511050d1d3634392/src/go/networking/go.mod#L9) and prepare a patch release.

Thank you for bringing this to our attention. I'll keep you updated with any further developments.

**Comment by Anutrix** [comment]
Fix seems to be in [gvisor-tap-vsock 0.8.2](https://github.com/containers/gvisor-tap-vsock/releases/tag/v0.8.2) now(https://github.com/containers/gvisor-tap-vsock/pull/450).
Maybe someone can test it out.

**Comment by jandubois** [comment]
> Fix seems to be in [gvisor-tap-vsock 0.8.2](https://github.com/containers/gvisor-tap-vsock/releases/tag/v0.8.2) now([containers/gvisor-tap-vsock#450](https://github.com/containers/gvisor-tap-vsock/pull/450)).
> Maybe someone can test it out.

Unfortunately that release seems to only fix the issues on macOS and Linux, but not the Windows problems.

In order to get 1.17.1 out we'll have to downgrade to 0.7.5 on Windows (but will upgrade to 0.8.2 on macOS and Linux). Hopefully the root cause on Windows can be found and fixed in time for 1.18.0.

**Comment by Nino-K** [comment]
We are planning to release patch version [1.17.1](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/untagged-f4ccc576f6922dd786ed) to address this issue. The root cause was an upgrade of gvisor-tap-vsock to v0.8.1. As part of the fix, we have downgraded it to v0.7.5, which should resolve the problem.

**Comment by luca-ballerini** [comment]
We are still seeing the same issue on macOS after upgrading to v. 1.17.1

**Comment by jandubois** [comment]
@luca-ballerini Thanks for the update. All the DNS refactoring in `gvisor-tap-vsock` has just been reverted in https://github.com/containers/gvisor-tap-vsock/pull/467.

Until that is included in a release, and Lima is updated to use the new version, and then Rancher Desktop is updated to use the new Lima, the best way to deal with this would be to revert back to 1.16.0. Sorry for all the mess!

**Comment by jnrsilva** [comment]
@jandubois I'm experiencing the same issue in Windows running v. 1.17.1.

Downgrade requires uninstalling current version. Will this delete all data (images, k8s resource, etc.)?

**Comment by jandubois** [comment]
> [@jandubois](https://github.com/jandubois) I'm experiencing the same issue in Windows running v. 1.17.1 without VM.

I assume you meant without VPN.

Could you clarify what your issue is? The 1.17.1 Windows release is using the old gvisor-tap-vsock version 0.7.5, so does not include the refactored DNS implementation.  So downgrading may not help with your issue. The downgrading suggestion was purely meant for macOS when users have issues with split-DNS, or local DNS resolvers.

It may be best to create a new issue specific to your problem, as this issue is collecting feedback from multiple users, whose root problem may be different.

> Downgrade requires uninstalling current version. Will this delete all data (images, k8s resource, etc.)?

Unfortunately it is not possible to downgrade Rancher Desktop without a factory reset (just like there is no way to downgrade an OS without a reinstall).

**Comment by Emerix** [comment]
Hiya! Any updates on a release 1.17.2 with a fix for this? It's still happening on MacOS. Looks like there is a new version of Lima out already. So if I understand this correctly it should be possible to do another release? We've downgraded to 1.16 for now =)

**Comment by jandubois** [comment]
> Looks like there is a new version of Lima out already.

There is a new gvisor-tap-vsock release that has the fix, and i've pulled it into Lima, but Lima 1.0.5 has not yet been released.

It is not clear yet if there will be a 1.17.2 patch release, or if this will have to wait until 1.18.0, given that testing releases takes a non-trivial amount of time as well.

**Comment by M0ns1gn0r** [comment]
I would really like to get the 1.17.2 patch release because just like @jnrsilva, I experience this problem with 1.17.1 on Windows, without an active VPN connection.

**Comment by M0ns1gn0r** [comment]
**Update**: I resolved my problem, it was caused by the enabled WSL Proxy to `host.docker.internal:6667`

![Image](https://github.com/user-attachments/assets/43e0f4c7-717d-46b0-8b6c-e64b96e4e3ed)

Looks like this setting was inherited from the old configuration which worked before that started to bring problems after several updates of Rancher Desktop.
