### ISSUE TITLE
cannot pull image

### ISSUE THREAD

**Issue by qzwzqty** [rancher-sandbox/rancher-desktop#8088]
### Actual Behavior

The following error occurs when pulling an image
Error response from daemon: failed to resolve reference "docker.io/timescale/timescaledb-ha:pg15": failed to do request: Head "https://registry-1.docker.io/v2/timescale/timescaledb-ha/manifests/pg15": EOF。
But with docker desktop don't have this problem

### Steps to Reproduce

1. install rancher-desktop 1.17.0
2. open, configure (kubernetes disabled, container engine: dockered)
3. rancher-desktop starts, default images visible in the images tab
4. open CMD
5. command : docker pull timescale/timescaledb-ha:pg15

### Result

![image](https://github.com/user-attachments/assets/e0205ffe-f555-4676-abc2-d9ecd894bea8)

### Expected Behavior

Expected result: docker image for timescale/timescaledb-ha:pg15 is pulled

### Rancher Desktop Version

1.17.0

### Rancher Desktop K8s Version

1.28.5

### Which container engine are you using?

moby (docker cli)

### What operating system are you using?

Windows

### Operating System / Build Version

Windows 11 Professional Edition 24H2

### What CPU architecture are you using?

x64

### Linux only: what package format did you use to install Rancher Desktop?

None

### Windows User Only

VPN clash

**Comment by AdrianMetzner** [comment]
I was having the same issue. The problem seems to be the dns resolution. In the docker engine a non functional local dns was used. I could employ a workaround by setting the nameserver to a publically known one (1.1.1.1, 8.8.8.8) in the provisioning of rancher desktop.

**Comment by matus-hustak** [comment]
I Have similar Issue. The issue is when using AWS SAM. The command is 'sam local start-api --debug'
After I install Rancher Desktop v 1.17 and run the sam command for the first time, everything works. But after any further 'sam local sart-api --debug' will end up in this error:  

Local image is up-to-date
Checking free port on 127.0.0.1:5823
Using local image: public.ecr.aws/lambda/python:3.11-rapid-x86_64.
Mounting /mnt/c/dr-hq/sam/drhq-sam/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated, inside runtime container
Exception raised during the execution
**Lambda functions containers initialization failed because of 500 Server Error for http+docker://localhost/v1.35/distribution/public.ecr.aws/lambda/python:3.11-x86_64/json: Internal Server Error ("Head
"https://public.ecr.aws/v2/lambda/python/manifests/3.11-x86_64": Get "https://public.ecr.aws/token/?scope=repository%3Alambda%2Fpython%3Apull&service=public.ecr.aws": EOF")**
Terminating all running warm containers
Terminate running warm container for Lambda Function 'HelloWorldFunction'

**Comment by Nino-K** [comment]
Hi, what you are seeing is most likely related to the DNS resolutions not functioning correctly behind the VPN in v1.17.0, please see my comment here: https://github.com/rancher-sandbox/rancher-desktop/issues/8055#issuecomment-2593611998.

**Comment by Nino-K** [comment]
We are planning to release patch version [1.17.1](https://github.com/rancher-sandbox/rancher-desktop/releases/tag/untagged-f4ccc576f6922dd786ed) to address this issue. The root cause was an upgrade of gvisor-tap-vsock to v0.8.1. As part of the fix, we have downgraded it to v0.7.5, which should resolve the problem.

**Comment by qzwzqty** [comment]
@Nino-K Hello, I have updated to the latest 1.18.2 version, but I still can't pull the image. 

![Image](https://github.com/user-attachments/assets/6489d9fb-1315-4cfa-ab4e-a8ccaa4e0efb)

**Comment by qzwzqty** [comment]
@Nino-K Hello，I reinstalled 1.18.2 and all components of Kubernetes started normally. However, the pull of images still failed. It seems that the proxy did not take effect.
![Image](https://github.com/user-attachments/assets/4c55cca6-da87-4acd-a508-f6394317a9ec)

![Image](https://github.com/user-attachments/assets/7bfcb2ba-3247-4f2e-846e-6ebcd111ebec)

**Comment by qzwzqty** [comment]
By disabling the built-in proxy configuration of Rancher Desktop and adding the proxy configuration to the ~/.bashrc file in WSL, I was able to pull images normally
